# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [3]:
tf.__version__

'2.10.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [8]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the 'Geography' column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_test)
#transform is used on the test or additional to scale it using the 
#distribution gotten from the training set
#fit:gets distribution of data it is applied to
#fit_transform:gets distribution and applies it in scaling

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


In [13]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


## Part 2 - Building the ANN

### Initializing the ANN

In [41]:
'The sequential class: helps initialize the ANN as a sequence of layers instead of as a computational graph e.g a Boltzmann machine'

'The sequential class: helps initialize the ANN as a sequence of layers instead of as a computational graph e.g a Boltzmann machine'

In [14]:
ann=tf.keras.models.Sequential()  

In [43]:
'Add input layer'. 'Below is the hidden layer'

SyntaxError: invalid syntax (279266690.py, line 1)

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#most important arg is the number of neurons i.e units
#best number is arrived at via experimentation
#The rectifier activation fxn is desirable because it does not activate all neurons at the same time

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))


### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))


## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
#optimizer,loss,metrics
#Best optimizers are capable of performing Stochastic Gradient Descent
#When carrying out binary classification, the loss fxn should be binary_crossentropy
#for non-binary classification, loss should be categorical crossentropy

### Training the ANN on the Training set

In [19]:
ann.fit(x_train,y_train,batch_size=32, epochs=100)
#rule of thumb:use 32

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5872 - accuracy: 0.7287
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4645 - accuracy: 0.8012
Epoch 3/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4390 - accuracy: 0.8061
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4268 - accuracy: 0.8110
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4179 - accuracy: 0.8196
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4095 - accuracy: 0.8254
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4017 - accuracy: 0.8288
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3931 - accuracy: 0.8341
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3836 - accuracy: 0.8388
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3743 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3296 - accuracy: 0.8655
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3290 - accuracy: 0.8666
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3291 - accuracy: 0.8673
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3292 - accuracy: 0.8633
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3289 - accuracy: 0.8661
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3291 - accuracy: 0.8654
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3291 - accuracy: 0.8658
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3290 - accuracy: 0.8669
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3288 - accuracy: 0.8665
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

In [20]:
x2=[[600,'France', 1, 40,2,60000,2,1,1,50000]]
x2=np.array(ct.fit_transform(x2))
print(x2)
ann.predict(x2)
#param in predict must be a 2D arr

[[1.0 600 1 40 2 60000 2 1 1 50000]]


ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

In [33]:
print(ann.predict(sc.transform([[1,0,0,600, 1, 40,2,60000,2,1,1,50000]]))>0.5)
#usually prints out a probability 
#to print out either 1 or 0 add a condtion >0.5 within the
#outermost bracket

1/1 [==============================] - 0s 38ms/step
[[False]]


In [29]:
print(y_test)

[0 1 0 ... 0 0 0]


### Predicting the Test set results

In [39]:
y_pred=ann.predict((x_test))>0.5

63/63 [==============================] - 0s 2ms/step


In [35]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


### Making the Confusion Matrix

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [42]:
cm=confusion_matrix(y_test,y_pred)

In [43]:
print(cm)

[[1499   96]
 [ 176  229]]


In [47]:
accu=accuracy_score(y_test,y_pred)

In [45]:
print(accu)

0.864
