<a href="https://colab.research.google.com/github/EwezuNgim/The_Shadow_Monarch/blob/main/Movie_Sentiment_Analysis(Lemma)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
!git clone https://github.com/IyanuSh/YOSM

Cloning into 'YOSM'...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 85 (delta 32), reused 27 (delta 6), pack-reused 0
Receiving objects: 100% (85/85), 584.50 KiB | 7.69 MiB/s, done.
Resolving deltas: 100% (32/32), done.


In [ ]:
import nltk
import os
import string

In [ ]:
%cd /content/YOSM/data/yosm/en
dev=pd.read_csv('dev.tsv',delimiter='\t')
test=pd.read_csv('test.tsv',delimiter='\t')
train=pd.read_csv('test.tsv',delimiter='\t')


/content/YOSM/data/yosm/en


In [ ]:
train.head()

en_review sentiment
0  One of Nollywood's Best Movies Thus Far. . . ....  positive
1  Charming and unusual in its cultural mix. . . ...  positive
2  Nice Movie. . . . Can it be better. Hell yeah ...  positive
3  I liked it a lot better than I tot I would. Es...  positive
4  Told with raw emotion and lurid violence, it t...  positive

In [ ]:
dev.head()

en_review sentiment
0  so cool. . . . This was so chilled. this movie...  positive
1  KOB is Number 1 Nollywood movie to me right no...  positive
2  This was an excellent movie. I would recommend...  positive
3  Love this Film. . I will enjoy watching it for...  positive
4                                     Love this Film  positive

In [ ]:
test.head()

en_review sentiment
0  One of Nollywood's Best Movies Thus Far. . . ....  positive
1  Charming and unusual in its cultural mix. . . ...  positive
2  Nice Movie. . . . Can it be better. Hell yeah ...  positive
3  I liked it a lot better than I tot I would. Es...  positive
4  Told with raw emotion and lurid violence, it t...  positive

In [ ]:
punctuations=set(string.punctuation)
punctuations

{'!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~'}

In [ ]:
#from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

**Data** **Cleaning**

In [ ]:
def clean_punctuations(data):
 for i in range(0,len(data)):
   word=data['en_review'][i]
   for item in punctuations:
     word= word.replace(item,'')
   data['en_review'][i]=word
   #punctuations removed
   #success
   corpus=[]
 #print("Here it comes, no punctuations:")
 #print(data['en_review'])
 for i in range(0,len(data)):
       #corpus.extend(train['en_review'][i].split(' '))
       corpus.append(data['en_review'][i])
       #punctuationless text stored
 nltk.download('stopwords')
 corpus_v2=[item for item in corpus if item.lower() not in set(stopwords.words('english'))]
 #store all reviews after stopwords have been removed
 nltk.download('wordnet')
 lemma=WordNetLemmatizer()
 clean_data=np.array([lemma.lemmatize(word) for word in corpus_v2])
 return clean_data

In [ ]:
for i in range(0,len(train)):
   word=train['en_review'][i]
   for item in punctuations:
     word= word.replace(item,'')
   train['en_review'][i]=word
train['en_review'][0]

'One of Nollywoods Best Movies Thus Far    And unlike the typical Nollywood classics I dreaded so much which ended in the climax and offering no resolutions 93 Days has a really good resolution'

Cleaning the training set

In [ ]:
c_train=clean_punctuations(train)
c_train

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...


array(['One of Nollywoods Best Movies Thus Far    And unlike the typical Nollywood classics I dreaded so much which ended in the climax and offering no resolutions 93 Days has a really good resolution',
       'Charming and unusual in its cultural mix    Above all it made me want to visit Lagos This is a preview of a world I want to live in If Nigerians and Indians can overcome their cultural differences so can we all',
       'Nice Movie    Can it be better Hell yeah But as one of the pioneer scifi movies it was good The messaging was apt  the lapses in some scenes understable per the end of the movie Its cool    Really didnt know what to expect    Would watch more stuff in this genre from Naija',
       'I liked it a lot better than I tot I would Especially the rather timid by Hollywood standard sex scenes There were however some part of the book I wish made to it to the movie  especially the part abt the braided head in the train from Kano bit Oh Kanene was exactly like how I pictur

Cleaning the test set

In [ ]:
c_test=clean_punctuations(test)
c_test
#cleaning text failed

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


array(['One of Nollywoods Best Movies Thus Far    And unlike the typical Nollywood classics I dreaded so much which ended in the climax and offering no resolutions 93 Days has a really good resolution',
       'Charming and unusual in its cultural mix    Above all it made me want to visit Lagos This is a preview of a world I want to live in If Nigerians and Indians can overcome their cultural differences so can we all',
       'Nice Movie    Can it be better Hell yeah But as one of the pioneer scifi movies it was good The messaging was apt  the lapses in some scenes understable per the end of the movie Its cool    Really didnt know what to expect    Would watch more stuff in this genre from Naija',
       'I liked it a lot better than I tot I would Especially the rather timid by Hollywood standard sex scenes There were however some part of the book I wish made to it to the movie  especially the part abt the braided head in the train from Kano bit Oh Kanene was exactly like how I pictur

Cleaning the validation set

In [ ]:
c_dev=clean_punctuations(dev)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
c_dev

array(['so cool    This was so chilled this movie was fun and enjoyable from the start Ive found no flaws to it maybe the introduction is a little corny but thats just taste this movie was light but meaningful highly recommended',
       'KOB is Number 1 Nollywood movie to me right now The story is way different and genuine Unveils what goes on in politics for real',
       'This was an excellent movie I would recommend it to anyone',
       'Love this Film  I will enjoy watching it for many years to come and the conversations that it will spark   The acting is very natural without melodrama and it feels very believable Overall the film was riveting and kept me really engaged',
       'Love this Film', 'A BRILLIANT MOVIE WITH A FEW PECKS',
       'Beautiful story that portrays Nigerian culture The story is so unique and unpredictable unlike an average Nigerian movie A must watch',
       'A must see very interesting story and well acted great collaboration with Hollywood and Nollywood 

**Encode the** **corpus**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
embeddings=CountVectorizer()
X_train=embeddings.fit_transform(c_train)
X_test=embeddings.transform(c_test)
X_dev=embeddings.transform(c_dev)

In [ ]:
X_train=X_train.toarray()
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_dev=X_dev.toarray()
X_dev

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(train['sentiment'])

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

**Build Model**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
KNN=KNeighborsClassifier(n_neighbors=5,metric='minkowski')
KNN.fit(X_train,y)

KNeighborsClassifier()

Performance on training set

In [ ]:
y_pred_train=KNN.predict(X_train)

In [ ]:
from sklearn.metrics import f1_score,accuracy_score, balanced_accuracy_score
f1=f1_score(y_pred_train,y)
f1

0.6136986301369863

In [ ]:
acc=accuracy_score(y_pred_train,y)
acc

0.718

In [ ]:
bal_acc=balanced_accuracy_score(y_pred_train,y)
bal_acc

0.8077357425183512

Performance on validation set

In [ ]:
y_pred=KNN.predict(X_dev)

In [ ]:
y_dev=le.transform(dev['sentiment'])
y_dev

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [ ]:
from sklearn.metrics import f1_score,accuracy_score, balanced_accuracy_score
f1=f1_score(y_pred,y_dev)
f1

0.29508196721311475

In [ ]:
acc=accuracy_score(y_pred,y_dev)
acc

0.57

In [ ]:
bal_acc=balanced_accuracy_score(y_pred,y_dev)
bal_acc

0.6787538304392238